Cartesian Gantry Slinger:
    title: "CartesianGSlinger"
    description: "Slinging gantrys and not beds"
    repository: "https://github.com/firesareba/Cartesian-Gantry-Slinger/blob/main/journal.md"
    file_name: cartesiangantryslinger.md
